---
RestartPolicy: ${restart_policy}
ImagePullPolicy: ${image.pullPolicy}
%{if length(keys(resources)) > 0 }
Resources: ${jsonencode(resources)}
%{ endif }
%{if env_from != "[]" }
EnvFrom: ${env_from}
%{ endif }
%{if env != "[]" }
Env: ${env}
%{ endif }

# command and args when given 
%{if command != "[]" && !debug }
Command: ${command}
%{ endif }
%{if args != "[]" && !debug }
Args: ${args}
%{ endif }

# if debug mode then tail to a black hole
%{ if debug }
Command: ["/bin/sh", "-c"]
Args: ["tail -f /dev/null"]
%{ endif }

%{if nodes.selector != null }
NodeSelector: ${jsonencode(nodes.selector)}
%{ endif }
%{if pod_annotations != "{}" }
PodAnnotations: ${pod_annotations}
%{ endif }
%{if pod_labels != "{}" }
PodLabels: ${pod_labels}
%{ endif }
%{if security_context != "{}" }
PodSecurityContext: ${security_context}
%{ endif }
%{if service_account_name != null }
ServiceAccountName: ${service_account_name}
%{ endif }
%{if host_network != null }
HostNetwork: ${host_network}
%{endif}
%{if volumes != "[]" }
Volumes: ${volumes}
%{ endif }
%{if volume_mounts != "[]" }
VolumesMounts: ${volume_mounts}
%{ endif }
%{if termination_grace_period != null }
terminationGracePeriodSeconds: ${termination_grace_period}
%{ endif }

# health check configuration
%{if health_check.enabled && !debug }
%{if health_check.liveliness.enabled }
LivenessProbe: 
  failureThreshold: ${coalesce(health_check.liveliness.failureThreshold, health_check.failureThreshold)}
  initialDelaySeconds: ${coalesce(health_check.liveliness.initialDelaySeconds, health_check.initialDelaySeconds)}
  periodSeconds: ${coalesce(health_check.liveliness.periodSeconds, health_check.periodSeconds)}
  successThreshold: ${coalesce(health_check.liveliness.successThreshold, health_check.successThreshold)}
  timeoutSeconds: ${coalesce(health_check.liveliness.timeoutSeconds, health_check.timeoutSeconds)}
  httpGet: 
    path: ${coalesce(health_check.liveliness.path, health_check.path)}
    port : ${coalesce(health_check.liveliness.port, health_check.port, port)}
%{ endif }
%{ if health_check.readiness.enabled }
ReadinessProbe: 
  failureThreshold: ${coalesce(health_check.readiness.failureThreshold, health_check.failureThreshold)}
  initialDelaySeconds: ${coalesce(health_check.readiness.initialDelaySeconds, health_check.initialDelaySeconds)}
  periodSeconds: ${coalesce(health_check.readiness.periodSeconds, health_check.periodSeconds)}
  successThreshold: ${coalesce(health_check.readiness.successThreshold, health_check.successThreshold)}
  timeoutSeconds : ${coalesce(health_check.readiness.timeoutSeconds, health_check.timeoutSeconds)}
  httpGet: 
    path: ${coalesce(health_check.readiness.path, health_check.path)}
    port: ${coalesce(health_check.readiness.port, health_check.port, port)}
%{ endif }
%{ if health_check.startup.enabled }
StartupProbe: 
  failureThreshold: ${coalesce(health_check.startup.failureThreshold, health_check.failureThreshold)}
  initialDelaySeconds: ${coalesce(health_check.startup.initialDelaySeconds, health_check.initialDelaySeconds)}
  periodSeconds: ${coalesce(health_check.startup.periodSeconds, health_check.periodSeconds)}
  successThreshold: ${coalesce(health_check.startup.successThreshold, health_check.successThreshold)}
  timeoutSeconds : ${coalesce(health_check.startup.timeoutSeconds, health_check.timeoutSeconds)}
  httpGet: 
    path: ${coalesce(health_check.startup.path, health_check.path)}
    port: ${coalesce(health_check.startup.port, health_check.port, port)}
%{ endif }
%{ endif }

# add all the sidecars into the additionalContainers key but only add the key if there are sidecars
%{ if length(sidecars) > 0 }
AdditionalContainers: 
%{ for sidecar in sidecars ~}
  - name: ${sidecar.name}
    image: ${sidecar.image}
%{ if length(lookup(sidecar, "command", [])) > 0 }
    command: ${jsonencode(sidecar.command)}
%{ endif }
%{ if length(lookup(sidecar, "args", [])) > 0 }
    args: ${jsonencode(sidecar.args)}
%{ endif }
%{ if sidecar.resources != null }
    resources: ${jsonencode(sidecar.resources)}
%{ endif }
%{ if sidecar.security_context != null }
    securityContext: ${jsonencode(sidecar.security_context)}
%{ endif }
%{ if length(lookup(sidecar, "ports", [])) > 0 }
    ports: ${jsonencode(sidecar.ports)}
%{ endif }
%{ if length(lookup(sidecar, "volume_mounts", [])) > 0 }
    volumeMounts: ${jsonencode(sidecar.volume_mounts)}
%{ endif }
%{ if length(lookup(sidecar, "env", {})) > 0 }
    env: 
%{ for key, value in sidecar.env ~}
      - name: ${key}
        value: ${value}
%{ endfor ~}
%{ endif }
%{ endfor ~}
%{ endif }
