name: Publish Version
description: Publishes a new version and tag. 
on: 
  workflow_dispatch: 
    inputs: 
      action: 
        description: Version to bump to
        default: patch
        type: choice
        options:
        - patch
        - minor
        - major
        - premajor
        - preminor
        - prepatch
      push: 
        description: Push changes to the repository
        default: false
        type: boolean
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Create GitHub App Token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_KEY }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
    
    - name: Bump Version
      id: bump
      uses: duplocloud/version-action@main
      with:
        token:  ${{ steps.app-token.outputs.token }}
        version: ${{ inputs.action }}
        push: ${{ inputs.push }}

    - name: Create Release
      id: release
      uses: softprops/action-gh-release@v2
      if: inputs.push == true
      with:
        name: ${{ steps.bump.outputs.tag }}
        tag_name: ${{ steps.bump.outputs.tag }}
        prerelease: false
        body: |
          [![Publish](${{ github.server_url }}/${{ github.repository }}/actions/workflows/publish.yml/badge.svg)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          ${{ steps.bump.outputs.release-notes }}

    - name: Summary 
      run: |
        cat <<EOF > $GITHUB_STEP_SUMMARY
        New Version: ${{ steps.bump.outputs.version }}
        Previous Version: ${{ steps.bump.outputs.previous-version }}

        Release Notes: 
        --------------
        ${{ steps.bump.outputs.release-notes }}
        EOF
