name: Publish Version
description: Publishes a new version and tag. 
on: 
  workflow_dispatch: 
    inputs: 
      action: 
        description: Version to bump to
        default: patch
        type: choice
        options:
        - patch
        - minor
        - major
        - premajor
        - preminor
        - prepatch
      push: 
        description: Push changes to the repository
        default: false
        type: boolean
jobs:

  bump:
    name: Bump Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
      previous-version: ${{ steps.bump.outputs.previous-version }}
      tag: ${{ steps.bump.outputs.tag }}
      release-notes: ${{ steps.bump.outputs.release-notes }}
      url: ${{ steps.registry.outputs.url }}
      badge: ${{ steps.registry.outputs.badge }}
    steps:

    - name: Create GitHub App Token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_KEY }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
    
    - name: Bump Version
      id: bump
      uses: duplocloud/version-bump@main
      with:
        token:  ${{ steps.app-token.outputs.token }}
        version: ${{ inputs.action }}
        push: ${{ inputs.push }}

    - name: Registry URL
      id: registry
      env:
        URL: https://registry.terraform.io/modules/duplocloud/components/duplocloud
        VERSION: ${{ steps.bump.outputs.version }}
      run: |
        URL="${URL}/${VERSION}"
        BADGE="[![TF Registry](https://img.shields.io/badge/TF-Registry-%23844FBA?style=flat-square&logo=terraform)](${URL})"
        echo "url=${URL}" >> $GITHUB_OUTPUT
        echo "badge=${BADGE}" >> $GITHUB_OUTPUT

      
    - name: Summary 
      run: |
        cat <<EOF > $GITHUB_STEP_SUMMARY
        ${{ steps.registry.outputs.badge }}
        New Version: ${{ steps.bump.outputs.version }}
        Previous Version: ${{ steps.bump.outputs.previous-version }}

        ## Release Notes: 
        --------------
        ${{ steps.bump.outputs.release-notes }}
        EOF

  release:
    name: Publish Release
    if: inputs.push
    needs: bump
    runs-on: ubuntu-latest
    environment: 
      name: terraform-registry
      url: ${{ needs.bump.outputs.url }}
    steps:
    - name: Create Release
      id: release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ needs.bump.outputs.tag }}
        tag_name: ${{ needs.bump.outputs.tag }}
        prerelease: false
        body: |
          [![Publish](${{ github.server_url }}/${{ github.repository }}/actions/workflows/publish.yml/badge.svg)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) ${{ needs.bump.outputs.badge }}

          ${{ needs.bump.outputs.release-notes }}
