name: 🧪 Test Modules

on:
  push:
    paths: 
    - modules/**
    branches: 
    - main
  pull_request:
    paths: 
    - modules/**

jobs:
  tf_module_test:
    name: Test
    uses: duplocloud/actions/.github/workflows/test-tf-modules.yml@main
    secrets: inherit
    with:
      environment: salesdemo
      tenant: tf-tests
